//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MovieSchedulerModel", "FK__Scheduler__Movie__0519C6AF", "Movie", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HomNayXemGi.Models.Movie), "Scheduler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HomNayXemGi.Models.Scheduler), true)]

#endregion

namespace HomNayXemGi.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MovieSchedulerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MovieSchedulerEntities object using the connection string found in the 'MovieSchedulerEntities' section of the application configuration file.
        /// </summary>
        public MovieSchedulerEntities() : base("name=MovieSchedulerEntities", "MovieSchedulerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MovieSchedulerEntities object.
        /// </summary>
        public MovieSchedulerEntities(string connectionString) : base(connectionString, "MovieSchedulerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MovieSchedulerEntities object.
        /// </summary>
        public MovieSchedulerEntities(EntityConnection connection) : base(connection, "MovieSchedulerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movie> Movies
        {
            get
            {
                if ((_Movies == null))
                {
                    _Movies = base.CreateObjectSet<Movie>("Movies");
                }
                return _Movies;
            }
        }
        private ObjectSet<Movie> _Movies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Scheduler> Schedulers
        {
            get
            {
                if ((_Schedulers == null))
                {
                    _Schedulers = base.CreateObjectSet<Scheduler>("Schedulers");
                }
                return _Schedulers;
            }
        }
        private ObjectSet<Scheduler> _Schedulers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Schedulers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchedulers(Scheduler scheduler)
        {
            base.AddObject("Schedulers", scheduler);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MovieSchedulerModel", Name="Movie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Movie CreateMovie(global::System.Int32 id)
        {
            Movie movie = new Movie();
            movie.Id = id;
            return movie;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producer
        {
            get
            {
                return _Producer;
            }
            set
            {
                OnProducerChanging(value);
                ReportPropertyChanging("Producer");
                _Producer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Producer");
                OnProducerChanged();
            }
        }
        private global::System.String _Producer;
        partial void OnProducerChanging(global::System.String value);
        partial void OnProducerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private global::System.String _Length;
        partial void OnLengthChanging(global::System.String value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DetailLink
        {
            get
            {
                return _DetailLink;
            }
            set
            {
                OnDetailLinkChanging(value);
                ReportPropertyChanging("DetailLink");
                _DetailLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DetailLink");
                OnDetailLinkChanged();
            }
        }
        private global::System.String _DetailLink;
        partial void OnDetailLinkChanging(global::System.String value);
        partial void OnDetailLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Info
        {
            get
            {
                return _Info;
            }
            set
            {
                OnInfoChanging(value);
                ReportPropertyChanging("Info");
                _Info = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Info");
                OnInfoChanged();
            }
        }
        private global::System.String _Info;
        partial void OnInfoChanging(global::System.String value);
        partial void OnInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MvSource
        {
            get
            {
                return _MvSource;
            }
            set
            {
                OnMvSourceChanging(value);
                ReportPropertyChanging("MvSource");
                _MvSource = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MvSource");
                OnMvSourceChanged();
            }
        }
        private global::System.String _MvSource;
        partial void OnMvSourceChanging(global::System.String value);
        partial void OnMvSourceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MovieSchedulerModel", "FK__Scheduler__Movie__0519C6AF", "Scheduler")]
        public EntityCollection<Scheduler> Schedulers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Scheduler>("MovieSchedulerModel.FK__Scheduler__Movie__0519C6AF", "Scheduler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Scheduler>("MovieSchedulerModel.FK__Scheduler__Movie__0519C6AF", "Scheduler", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MovieSchedulerModel", Name="Scheduler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Scheduler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Scheduler object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Scheduler CreateScheduler(global::System.Int32 id)
        {
            Scheduler scheduler = new Scheduler();
            scheduler.ID = id;
            return scheduler;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MovieID
        {
            get
            {
                return _MovieID;
            }
            set
            {
                OnMovieIDChanging(value);
                ReportPropertyChanging("MovieID");
                _MovieID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MovieID");
                OnMovieIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MovieID;
        partial void OnMovieIDChanging(Nullable<global::System.Int32> value);
        partial void OnMovieIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CumRap
        {
            get
            {
                return _CumRap;
            }
            set
            {
                OnCumRapChanging(value);
                ReportPropertyChanging("CumRap");
                _CumRap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CumRap");
                OnCumRapChanged();
            }
        }
        private global::System.String _CumRap;
        partial void OnCumRapChanging(global::System.String value);
        partial void OnCumRapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenRap
        {
            get
            {
                return _TenRap;
            }
            set
            {
                OnTenRapChanging(value);
                ReportPropertyChanging("TenRap");
                _TenRap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenRap");
                OnTenRapChanged();
            }
        }
        private global::System.String _TenRap;
        partial void OnTenRapChanging(global::System.String value);
        partial void OnTenRapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NgayChieu
        {
            get
            {
                return _NgayChieu;
            }
            set
            {
                OnNgayChieuChanging(value);
                ReportPropertyChanging("NgayChieu");
                _NgayChieu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NgayChieu");
                OnNgayChieuChanged();
            }
        }
        private global::System.String _NgayChieu;
        partial void OnNgayChieuChanging(global::System.String value);
        partial void OnNgayChieuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SuatChieu
        {
            get
            {
                return _SuatChieu;
            }
            set
            {
                OnSuatChieuChanging(value);
                ReportPropertyChanging("SuatChieu");
                _SuatChieu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SuatChieu");
                OnSuatChieuChanged();
            }
        }
        private global::System.String _SuatChieu;
        partial void OnSuatChieuChanging(global::System.String value);
        partial void OnSuatChieuChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MovieSchedulerModel", "FK__Scheduler__Movie__0519C6AF", "Movie")]
        public Movie Movie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("MovieSchedulerModel.FK__Scheduler__Movie__0519C6AF", "Movie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("MovieSchedulerModel.FK__Scheduler__Movie__0519C6AF", "Movie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Movie> MovieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("MovieSchedulerModel.FK__Scheduler__Movie__0519C6AF", "Movie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Movie>("MovieSchedulerModel.FK__Scheduler__Movie__0519C6AF", "Movie", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
